services:
  - type: web
    name: realtime-code-editor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: LOG_LEVEL
        value: info
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: INLINE_RUNTIME_CHUNK
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - Dockerfile
        - server-simple.js
        - config/**
        - services/**
        - routes/**
        - middleware/**
        - models/**
      ignoredPaths:
        - "*.md"
        - "test*"
        - "debug*"
        - "fix*"
        - "Dockerfile.*"
        - docker-compose* 