services:
  - type: web
    name: realtime-code-editor
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: info
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: INLINE_RUNTIME_CHUNK
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      # AI Code Review Configuration (Optional)
      # Add these in Render Dashboard Environment Variables section:
      # GEMINI_API_KEY: your_gemini_api_key_here (FREE option)
      # OPENAI_API_KEY: your_openai_api_key_here (PAID option)  
      # AI_PROVIDER: gemini (or 'openai')
      # Redis Configuration (Optional for scaling)
      # REDIS_URL: your_redis_url_here
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - server*.js
        - config/**
        - services/**
        - routes/**
        - middleware/**
        - models/**
        - build/**
      ignoredPaths:
        - "*.md"
        - "test*"
        - "debug*"
        - "fix*"
        - "Dockerfile*"
        - docker-compose*
        - logs/**
        - node_modules/** 